POST http://localhost:8000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "andres.dosantosbritoamaral@gmail.com",
  "password": "dB@67oiu",
  "firstName": "Andres",
  "lastName": "dos Santos"
}

###

GET http://localhost:8000/api/v1/specialty
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9mZXNzaW9uYWxJZCI6IjQ2OTYxNjA4LTNiZmQtNDA5YS04NjBlLWRhZjBiMTg2ZjdiMSIsImlhdCI6MTc0NDMxNDYwNiwiZXhwIjoxNzQ0OTE5NDA2fQ.jtWgFGr2wmnBgeYvMjS51cWdYyF2SUNV2TgM26niNvY;
